#!/bin/bash
#
# multipleOceanStressors   gunicorn server from multipleOceanStressors.py
#
# chkconfig: 5 70 30
# description: A gunicorn server for multipleOceanStressors project
# processname: multipleOceanStressors 

# ==================================
# sudo cp multipleOceanStressors /etc/init.d/
# sudo chkconfig --add multipleOceanStressors
# sudo service multipleOceanStressors {start|stop|status|restart}

# ==================================
# Source function library.
. /etc/init.d/functions

RETVAL=0
service=multipleOceanStressors
DIR=/var/www/html/ScientificApps/dev/forge_patrick/multipleOceanStressors

case "$1" in
    start)
        echo "Starting $service"
        if [ ! -e /var/run/$service.pid ]; then
                export PATH="/home/webportals/anaconda2/bin:$PATH"
                . /home/webportals/pyferret-7.1.0-RHEL6-64/ferret_paths.sh
                $DIR/multipleOceanStressors.py &
                echo $! > /var/run/$service.pid
        else
           echo $service is already running
           exit 1
        fi
        ;;
    stop)
        echo "Shutting down $service"
        kill `cat /var/run/$service.pid`
        rm /var/run/$service.pid
        ;;
    status)
        echo "Checking $service status"
        if [ -e /var/run/$service.pid ]; then
           echo $service is running, pid=`cat /var/run/$service.pid`
        else
           echo $service is NOT running
           exit 1
        fi
        ;;
    restart)
        $0 stop
        sleep 5s
        $0 start
        ;;
    *)
        echo "Usage: $service {start|stop|status|restart}"
        exit 1
        ;;
esac
exit
